on:
  release:
    types: [released]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - github-actions
name: Check & Deploy
jobs:
  R-CMD-Check:
    uses: ./.github/workflows/R-CMD-check.yaml
  pkgdown:
    needs: R-CMD-check
    if: github.event_name == 'push'
    uses: ./.github/workflows/pkgdown.yaml
  deploy-latest:
    needs: pkgdown
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yaml
    with:
      rsconnect-app-name: "PRISMA_flowdiagram_latest"
      working-directory: "./inst/shiny-examples/PRISMA_flowdiagram"
      environment: "Latest"
      environment-url: "https://chriscpritchard.shinyapps.io/PRISMA_flowdiagram_latest"
    secrets:
      rsconnect-account-name: ${{ secrets.SHINY_ACC_NAME }}
      rsconnect-account-token: ${{ secrets.TOKEN }}
      rsconnect-account-secret: ${{ secrets.SECRET }}