on:
  workflow_call:
    inputs:
      working-directory:
        description: 'The directory the shiny app is located in within your repository'
        default: './'
      rsconnect-app-name:
        description: 'The name of the app to deploy'
        required: true
      rsconnect-account-name:
        description: 'The account name for publishing'
        required: false
      environment:
        description: 'The environment to run the workflow'
        required: true
      environment-url:
        description: 'The URL for the environment'
    secrets:
      TOKEN:
        description: 'The token for publishing to ShinyApps.io'
        required: false
      SECRET:
        description: 'The secret for publishing to ShinyApps.io'
        required: false

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment-url }}
    env:
      SHINY_ACC_NAME: ${{ secrets.SHINY_ACC_NAME }}
      SHINY_APP_NAME: ${{ inputs.rsconnect-app-name }}
      TOKEN: ${{ secrets.TOKEN }}
      SECRET: ${{ secrets.SECRET }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            rsconnect
            devtools
            github::${{ github.repository }}@${{ github.ref }}
      - name: Deploy to ShinyApps.io
        working-directory: ${{ inputs.working-directory }}
        run: |
          library(rsconnect)
          setAccountInfo(name = Sys.getenv("SHINY_ACC_NAME", unset = NA), token = Sys.getenv("TOKEN", unset = NA), secret = Sys.getenv("SECRET", unset=NA))
          deployApp(appName = Sys.getenv("SHINY_APP_NAME", unset = NA))
        shell: Rscript {0}