on:
  release:
    types: [released]

name: Deploy to ShinyApps

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      SHINY_ACC_NAME: ${{ secrets.SHINY_ACC_NAME }}
      TOKEN: ${{secrets.TOKEN}}
      SECRET: ${{secrets.SECRET}}
      ANALYTICS_JS: ${{secrets.ANALYTICS_JS}}
      ANALYTICS_ID: ${{secrets.ANALYTICS_ID}}
      ANALYTICS: TRUE
    steps:
      - uses: actions/checkout@v2

      - name: Enable umami analytics
        working-directory: ./inst/shiny-examples/PRISMA_flowdiagram
        run: |
          sed -i 's/REPLACE_WITH_REAL_URL/$ANALYTICS_JS/g' ./www/analytics.R
          sed -i 's/REPLACE_WITH_REAL_ID/$ANALYTICS_ID/g' ./www/analytics.R
          sed -i '/INSERT_ANALYTICS_CODE/r ./www/analytics.R' ./app.R
          cat ./www/analytics.R
          cat ./app.R |grep -B 10 -A 10 INSERT_ANALYTICS_CODE

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          install.packages(c("rsconnect","shiny","shinyjs","rsvg","DT","rio","devtools"))
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy to shinyapps.io
        working-directory: ./inst/shiny-examples/PRISMA_flowdiagram
        run: |
          library(rsconnect)
          setAccountInfo(name = Sys.getenv("SHINY_ACC_NAME", unset=NA), token = Sys.getenv("TOKEN", unset=NA), secret = Sys.getenv("SECRET", unset=NA))
          deployApp(appName = "prisma_flowdiagram")
        shell: Rscript {0}
